@startuml


class Animals {
    +name: String
    +age: int
}

class PackAnimals extends Animals {

}

class Horses extends PackAnimals {

}

class Camels extends PackAnimals {
    
}

class Donkeys extends PackAnimals {
    
}

class PetAnimals extends Animals {

}

class Dogs extends PetAnimals {

}

class Cats extends PetAnimals {
    
}

class Hamsters extends PetAnimals {
    
}

@enduml